package com.WUT.RW.model;

import java.io.Serializable;

/**
 * GangWei モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Gangwei implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** GangWeiXuQiu. */
	private String gangweixuqiu;

	/** GangWeiMing. */
	private String gangweiming;

	/** ZhenDuiRenQun. */
	private String zhenduirenqun;

	/** GongZuoShiJian. */
	private String gongzuoshijian;

	/** GongZi. */
	private String gongzi;

	/**
	 * コンストラクタ.
	 */
	public Gangwei() {
	}

	/**
	 * GangWeiXuQiu を設定します.
	 * 
	 * @param gangweixuqiu
	 *            GangWeiXuQiu
	 */
	public void setGangweixuqiu(String gangweixuqiu) {
		this.gangweixuqiu = gangweixuqiu;
	}

	/**
	 * GangWeiXuQiu を取得します.
	 * 
	 * @return GangWeiXuQiu
	 */
	public String getGangweixuqiu() {
		return this.gangweixuqiu;
	}

	/**
	 * GangWeiMing を設定します.
	 * 
	 * @param gangweiming
	 *            GangWeiMing
	 */
	public void setGangweiming(String gangweiming) {
		this.gangweiming = gangweiming;
	}

	/**
	 * GangWeiMing を取得します.
	 * 
	 * @return GangWeiMing
	 */
	public String getGangweiming() {
		return this.gangweiming;
	}

	/**
	 * ZhenDuiRenQun を設定します.
	 * 
	 * @param zhenduirenqun
	 *            ZhenDuiRenQun
	 */
	public void setZhenduirenqun(String zhenduirenqun) {
		this.zhenduirenqun = zhenduirenqun;
	}

	/**
	 * ZhenDuiRenQun を取得します.
	 * 
	 * @return ZhenDuiRenQun
	 */
	public String getZhenduirenqun() {
		return this.zhenduirenqun;
	}

	/**
	 * GongZuoShiJian を設定します.
	 * 
	 * @param gongzuoshijian
	 *            GongZuoShiJian
	 */
	public void setGongzuoshijian(String gongzuoshijian) {
		this.gongzuoshijian = gongzuoshijian;
	}

	/**
	 * GongZuoShiJian を取得します.
	 * 
	 * @return GongZuoShiJian
	 */
	public String getGongzuoshijian() {
		return this.gongzuoshijian;
	}

	/**
	 * GongZi を設定します.
	 * 
	 * @param gongzi
	 *            GongZi
	 */
	public void setGongzi(String gongzi) {
		this.gongzi = gongzi;
	}

	/**
	 * GongZi を取得します.
	 * 
	 * @return GongZi
	 */
	public String getGongzi() {
		return this.gongzi;
	}


}
