package com.WUT.RW.model;

import java.io.Serializable;

/**
 * GongSi モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Gongsi implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** GongSiMing. */
	private String gongsiming;

	/** GongSiGuanWang. */
	private String gongsiguanwang;

	/** GongSiLaoBanMing. */
	private String gongsilaobanming;

	/** GongSiDianHua. */
	private String gongsidianhua;

	/** GongSiDiZhi. */
	private String gongsidizhi;

	/**
	 * コンストラクタ.
	 */
	public Gongsi() {
	}

	/**
	 * GongSiMing を設定します.
	 * 
	 * @param gongsiming
	 *            GongSiMing
	 */
	public void setGongsiming(String gongsiming) {
		this.gongsiming = gongsiming;
	}

	/**
	 * GongSiMing を取得します.
	 * 
	 * @return GongSiMing
	 */
	public String getGongsiming() {
		return this.gongsiming;
	}

	/**
	 * GongSiGuanWang を設定します.
	 * 
	 * @param gongsiguanwang
	 *            GongSiGuanWang
	 */
	public void setGongsiguanwang(String gongsiguanwang) {
		this.gongsiguanwang = gongsiguanwang;
	}

	/**
	 * GongSiGuanWang を取得します.
	 * 
	 * @return GongSiGuanWang
	 */
	public String getGongsiguanwang() {
		return this.gongsiguanwang;
	}

	/**
	 * GongSiLaoBanMing を設定します.
	 * 
	 * @param gongsilaobanming
	 *            GongSiLaoBanMing
	 */
	public void setGongsilaobanming(String gongsilaobanming) {
		this.gongsilaobanming = gongsilaobanming;
	}

	/**
	 * GongSiLaoBanMing を取得します.
	 * 
	 * @return GongSiLaoBanMing
	 */
	public String getGongsilaobanming() {
		return this.gongsilaobanming;
	}

	/**
	 * GongSiDianHua を設定します.
	 * 
	 * @param gongsidianhua
	 *            GongSiDianHua
	 */
	public void setGongsidianhua(String gongsidianhua) {
		this.gongsidianhua = gongsidianhua;
	}

	/**
	 * GongSiDianHua を取得します.
	 * 
	 * @return GongSiDianHua
	 */
	public String getGongsidianhua() {
		return this.gongsidianhua;
	}

	/**
	 * GongSiDiZhi を設定します.
	 * 
	 * @param gongsidizhi
	 *            GongSiDiZhi
	 */
	public void setGongsidizhi(String gongsidizhi) {
		this.gongsidizhi = gongsidizhi;
	}

	/**
	 * GongSiDiZhi を取得します.
	 * 
	 * @return GongSiDiZhi
	 */
	public String getGongsidizhi() {
		return this.gongsidizhi;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((gongsiming == null) ? 0 : gongsiming.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Gongsi other = (Gongsi) obj;
		if (gongsiming == null) {
			if (other.gongsiming != null) {
				return false;
			}
		} else if (!gongsiming.equals(other.gongsiming)) {
			return false;
		}

		return true;
	}

}
