package com.WUT.RW.model;

import java.io.Serializable;

/**
 * YongHu モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Yonghu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** YongHuMing. */
	private String yonghuming;

	/** YongHuDianHua. */
	private String yonghudianhua;

	/** YongHuXingBie. */
	private String yonghuxingbie;

	/** YongHuDiZhi. */
	private String yonghudizhi;

	/** YongHuEmailDiZhi. */
	private String yonghuemaildizhi;

	/**
	 * コンストラクタ.
	 */
	public Yonghu() {
	}

	/**
	 * YongHuMing を設定します.
	 * 
	 * @param yonghuming
	 *            YongHuMing
	 */
	public void setYonghuming(String yonghuming) {
		this.yonghuming = yonghuming;
	}

	/**
	 * YongHuMing を取得します.
	 * 
	 * @return YongHuMing
	 */
	public String getYonghuming() {
		return this.yonghuming;
	}

	/**
	 * YongHuDianHua を設定します.
	 * 
	 * @param yonghudianhua
	 *            YongHuDianHua
	 */
	public void setYonghudianhua(String yonghudianhua) {
		this.yonghudianhua = yonghudianhua;
	}

	/**
	 * YongHuDianHua を取得します.
	 * 
	 * @return YongHuDianHua
	 */
	public String getYonghudianhua() {
		return this.yonghudianhua;
	}

	/**
	 * YongHuXingBie を設定します.
	 * 
	 * @param yonghuxingbie
	 *            YongHuXingBie
	 */
	public void setYonghuxingbie(String yonghuxingbie) {
		this.yonghuxingbie = yonghuxingbie;
	}

	/**
	 * YongHuXingBie を取得します.
	 * 
	 * @return YongHuXingBie
	 */
	public String getYonghuxingbie() {
		return this.yonghuxingbie;
	}

	/**
	 * YongHuDiZhi を設定します.
	 * 
	 * @param yonghudizhi
	 *            YongHuDiZhi
	 */
	public void setYonghudizhi(String yonghudizhi) {
		this.yonghudizhi = yonghudizhi;
	}

	/**
	 * YongHuDiZhi を取得します.
	 * 
	 * @return YongHuDiZhi
	 */
	public String getYonghudizhi() {
		return this.yonghudizhi;
	}

	/**
	 * YongHuEmailDiZhi を設定します.
	 * 
	 * @param yonghuemaildizhi
	 *            YongHuEmailDiZhi
	 */
	public void setYonghuemaildizhi(String yonghuemaildizhi) {
		this.yonghuemaildizhi = yonghuemaildizhi;
	}

	/**
	 * YongHuEmailDiZhi を取得します.
	 * 
	 * @return YongHuEmailDiZhi
	 */
	public String getYonghuemaildizhi() {
		return this.yonghuemaildizhi;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((yonghuming == null) ? 0 : yonghuming.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Yonghu other = (Yonghu) obj;
		if (yonghuming == null) {
			if (other.yonghuming != null) {
				return false;
			}
		} else if (!yonghuming.equals(other.yonghuming)) {
			return false;
		}

		return true;
	}

}
