package com.WUT.RW.model;

import java.io.Serializable;
import java.util.Date;

/**
 * ZhaoPinHui モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Zhaopinhui implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ZhaoPingHuiDiDian. */
	private String zhaopinghuididian;

	/** ZhaoPinHuiShiJian. */
	private Date zhaopinhuishijian;

	/** ZhaoPinHuiName. */
	private String zhaopinhuiname;

	/**
	 * コンストラクタ.
	 */
	public Zhaopinhui() {
	}

	/**
	 * ZhaoPingHuiDiDian を設定します.
	 * 
	 * @param zhaopinghuididian
	 *            ZhaoPingHuiDiDian
	 */
	public void setZhaopinghuididian(String zhaopinghuididian) {
		this.zhaopinghuididian = zhaopinghuididian;
	}

	/**
	 * ZhaoPingHuiDiDian を取得します.
	 * 
	 * @return ZhaoPingHuiDiDian
	 */
	public String getZhaopinghuididian() {
		return this.zhaopinghuididian;
	}

	/**
	 * ZhaoPinHuiShiJian を設定します.
	 * 
	 * @param zhaopinhuishijian
	 *            ZhaoPinHuiShiJian
	 */
	public void setZhaopinhuishijian(Date zhaopinhuishijian) {
		this.zhaopinhuishijian = zhaopinhuishijian;
	}

	/**
	 * ZhaoPinHuiShiJian を取得します.
	 * 
	 * @return ZhaoPinHuiShiJian
	 */
	public Date getZhaopinhuishijian() {
		return this.zhaopinhuishijian;
	}

	/**
	 * ZhaoPinHuiName を設定します.
	 * 
	 * @param zhaopinhuiname
	 *            ZhaoPinHuiName
	 */
	public void setZhaopinhuiname(String zhaopinhuiname) {
		this.zhaopinhuiname = zhaopinhuiname;
	}

	/**
	 * ZhaoPinHuiName を取得します.
	 * 
	 * @return ZhaoPinHuiName
	 */
	public String getZhaopinhuiname() {
		return this.zhaopinhuiname;
	}


}
