
/* Drop Tables */

DROP TABLE GANGWEI;
DROP TABLE GONGSI;
DROP TABLE TOUDIXINXI;
DROP TABLE YONGHU;
DROP TABLE ZHAOPINHUI;

/* Create Tables */

CREATE TABLE GANGWEI
(
	GANGWEIMING CHAR(20),
	GANGWEIXUQIU CHAR(100),
	ZHENDUIRENQUN CHAR(50),
	GONGZUOSHIJIAN CHAR(10),
	GONGZI CHAR(20)
);


CREATE TABLE GONGSI
(
	GONGSIMING VARCHAR(10) NOT NULL,
	GONGSIGUANWANG CHAR(30),
	GONGSILAOBANMING CHAR(10),
	GONGSIDIANHUA CHAR(12),
	GONGSIDIZHI CHAR(40),
	PRIMARY KEY (GONGSIMING)
);


CREATE TABLE TOUDIXINXI
(
	TOUDIRENXINGMING VARCHAR(20),
	XUELI VARCHAR(5),
	ZHUXIU CHAR(10),
	GONGZUOJINGYAN CHAR(100),
	ZIWOPINGJIA VARCHAR(200)
);


CREATE TABLE YONGHU
(
	YONGHUMING VARCHAR(20) NOT NULL,
	YONGHUDIANHUA CHAR(12),
	YONGHUXINGBIE CHAR(2),
	YONGHUDIZHI CHAR(40),
	YONGHUEMAILDIZHI CHAR(30),
	PRIMARY KEY (YONGHUMING)
);


CREATE TABLE ZHAOPINHUI
(
	ZHAOPINGHUIDIDIAN CHAR(150),
	ZHAOPINHUISHIJIAN DATE,
	ZHAOPINHUINAME CHAR(50)
);

insert into yonghu
values('杜碧云','17340577812','女','武昌理工学院','1405772794@qq.com');



